#!/usr/bin/env bash
#
# `bootstrap` installs things.

set -e

SCRIPTS_ROOT="$(dirname "$0")"
source "${SCRIPTS_ROOT}"/util.sh
source "${SCRIPTS_ROOT}"/logic/symlink-topic.sh

cd "${SCRIPTS_ROOT}"/..
DOTFILES_ROOT=$(pwd -P)

install_dotfiles() {
  info 'Installing dotfiles…'

  # NOTE: We use a mapfile here because we need to read user input in the loop and
  #   if we used `find … | while read …` we'd receive the result of `find` as "user input".
  #   Also we can't use `find -exec` because `symlink_topic` is not in the `PATH`.
  mapfile -d '' topics < <(find -H * -maxdepth 0 -type d -print0)
  for topic in "${topics[@]}"; do
    symlink_topic "$topic"
  done

  success 'Successfully installed dotfiles.\n'
}

install_dependencies() {
	# If we're on a Mac, let's install and setup homebrew.
	if [ "$(uname -s)" == 'Darwin' ]; then
	  info 'Installing dependencies…'
	  if edo _log_as_info source bin/dot; then
	    success 'Successfully installed dependencies.\n'
	  else
	    die 'Error installing dependencies.'
	  fi
	fi
}

install_dotfiles
install_dependencies

success 'All installed!'
