#!/usr/bin/env bash
#
# Move into a new session.

set -e

SCRIPTS_ROOT="$(dirname "$0")"
source "${SCRIPTS_ROOT}"/util.sh
source "${SCRIPTS_ROOT}"/logic/symlink-topic.sh

cd "${SCRIPTS_ROOT}"/..
DOTFILES_ROOT=$(pwd -P)

for topic in "$@"; do
	if ! [ -d "$topic" ]; then
		error "Topic $(format_url $topic) not found."
		continue
	fi
	symlink_topic "$topic"

	success "Successfully symlinked topic $(format_url $topic)"
done
